site_name: StreamSDR
site_description: Documentation for StreamSDR, the server for SDR radios
site_author: Orry Verducci
site_url: https://docs.streamsdr.io/

repo_name: StreamSDR's GitHub
repo_url: https://github.com/orryverducci/StreamSDR/

theme:
  name: readthedocs

nav:
  - About: index.md
  - Installing and Uninstalling: installing.md
  - Using StreamSDR: using.md
  - Getting Help: support.md
