#
# Builds the application and uploads artifacts
#

name: Build Application

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  win-x64-build:
    name: Windows x64 Build
    runs-on: windows-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build libusb
        run: ./build.sh -t BuildLibusb

      - name: Build rtl-sdr
        run: ./build.sh --exclusive -t BuildRtlSdr

      - name: Build StreamSDR
        run: ./build.sh -t BuildStreamSDR

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          path: artifacts/win-x64

  linux-x64-build:
    name: Linux x64 Build
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build StreamSDR
        run: ./build.sh -t BuildStreamSDR

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: artifacts/linux-x64

  macos-x64-build:
    name: macOS x64 Build
    runs-on: macos-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build StreamSDR
        run: ./build.sh -t BuildStreamSDR

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-x64
          path: artifacts/osx-x64
