#
# Checks the formatting of the code using dotnet-format
#

name: Formatting Check

on:
  push:
    paths:
      - 'build/**'
      - 'src/**'
  pull_request:
    paths:
      - 'build/**'
      - 'src/**'

jobs:
  dotnet-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Add dotnet-format problem matcher
        uses: renanrcp/dotnet-format-problem-matcher@v.1.3.2

      - name: Run dotnet-format
        run: dotnet format --verify-no-changes
